# Generated by Django 3.0.8 on 2020-10-04 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PartyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_name', models.TextField()),
                ('_password', models.CharField(editable=False, max_length=128, unique=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('comments_or_questions', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GuestsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('is_attending', models.NullBooleanField(default=None)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rsvp.PartyModel')),
            ],
        ),
    ]
