# Generated by Django 3.0.8 on 2020-10-25 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0003_auto_20201025_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestsmodel',
            name='first_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='guestsmodel',
            name='last_name',
            field=models.TextField(),
        ),
    ]
